version: '3.9'
services:

  nginx:
    build: 
      context: .
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: 
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo
    environment:
       - MONGO_INITDB_ROOT_USERNAME=mohsen
       - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - flashCardDb:/data/db
volumes:
  flashCardDb: