
services:

  nginx:
    build: 
      context: .
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: 
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - BOT_TOKEN=7779893384:AAFy-5W_0-N7HHbRKC8Bo9fBkNmiYwl2wNk
    depends_on:
      - mongo
    command: npm run dev

  react:
      build: 
        context: ./client
      ports:
        - "3001:3000"
      volumes:
      - ./client:/client
      - /client/node_modules

  telegram-bot:
    build:
      context: ./telegram-bot
    volumes:
      - ./telegram-bot:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - BOT_TOKEN=7779893384:AAFy-5W_0-N7HHbRKC8Bo9fBkNmiYwl2wNk
    ports:
      - "3002:3000"

  mongo:
    image: mongo
    environment:
       - MONGO_INITDB_ROOT_USERNAME=mohsen
       - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - flashCardDb:/data/db
      
volumes:
  flashCardDb: