version: '3.9'
services:

  nginx:
    build: 
      context: .
    ports:
      - "80:80"
    depends_on:
      - node-server

  server:
    build:
      context: ./api
      target: production 
    environment:
      - NODE_ENV=production 
    depends_on:
      - mongo
    restart: unless-stopped 

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mohsen
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - flashCardDb:/data/db
volumes:
  flashCardDb: